require: rubocop-rspec

RSpec/MultipleExpectations:
  Max: 4
RSpec/ContextWording:
  Enabled: false
RSpec/FilePath:
  SpecSuffixOnly: true
RSpec/InstanceVariable:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - attempt.gemspec
    - Rakefile
    - Gemfile

Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
