plugins: rubocop-rspec

RSpec/BeforeAfterAll:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 4
RSpec/ContextWording:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/SpecFilePathSuffix:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - attempt.gemspec
    - Rakefile
    - Gemfile

Style/BlockDelimiters:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/Semicolon:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/CaseIndentation:
  IndentOneStep: true
Layout/SpaceBeforeBlockBraces:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
Metrics/BlockNesting:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'

Security/MarshalLoad:
  Enabled: false
